# Generated by Django 6.0.3 on 2026-04-02 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0029_alter_ballot_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballotsection",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="side",
            field=models.CharField(
                choices=[("P", "Petitioner"), ("D", "Respondent"), ("other", "Swing")],
                max_length=5,
                null=True,
            ),
        ),
    ]
