# Generated by Django 6.0.3 on 2026-04-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0030_alter_ballotsection_score_alter_character_side"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paradigm",
            name="experience_years",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="How many years of moot court experience do you have?",
                max_digits=3,
            ),
        ),
    ]
