# Generated by Codex on 2026-04-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0031_alter_paradigm_experience_years"),
        ("tourney", "0038_tournament_predetermined_speakers"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="byebuster_excluded_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excluded_byebuster_ballots",
                related_query_name="excluded_byebuster_ballot",
                to="tourney.team",
            ),
        ),
    ]
