# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0033_ballot_counted_for_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotsection",
            name="comment_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
