# Generated by Django 6.0.3 on 2026-04-02 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0030_alter_tournament_hide_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judge",
            name="judge_friends",
            field=models.ManyToManyField(blank=True, to="tourney.judge"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="p_choice",
            field=models.CharField(
                choices=[("Petitioner", "Petitioner")],
                help_text="Petitioner side label",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="rank_nums",
            field=models.IntegerField(
                default=5,
                help_text="How many competitors do judges rank?",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="wit_nums",
            field=models.IntegerField(
                default=2,
                help_text="Moot court uses two speakers per side.",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
    ]
