# Generated by Django 6.0.3 on 2026-04-02 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tourney",
            "0031_alter_judge_judge_friends_alter_tournament_p_choice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="elim_break",
            field=models.CharField(
                choices=[
                    ("none", "No Elimination Rounds"),
                    ("octas", "Octas"),
                    ("quarters", "Quarters"),
                    ("semis", "Semis"),
                ],
                default="none",
                help_text="How far should the break clear before finals?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="prelim_rounds",
            field=models.IntegerField(
                default=4,
                help_text="How many preliminary rounds should be tabbed before elimination rounds?",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pairing",
            name="round_num",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
    ]
