# Generated by Django 6.0.3 on 2026-04-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tourney",
            "0033_alter_pairing_round_num_alter_tournament_elim_break_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
