# Generated by Django 6.0.3 on 2026-04-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0034_competitor_total_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="judge",
            name="available_round6",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="judge",
            name="available_round7",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="judge",
            name="available_round8",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="judge",
            name="available_round9",
            field=models.BooleanField(default=False),
        ),
    ]
