# Generated by Django 6.0.3 on 2026-04-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0035_judge_available_round6_judge_available_round7_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round1",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round2",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round3",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round4",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round5",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round6",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round7",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round8",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_judges_round9",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tournament",
            name="required_judges",
            field=models.IntegerField(
                default=2,
                help_text="How many judges must be assigned before a round can be finalized?",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="judges",
            field=models.IntegerField(
                default=2, help_text="How many ballots do you count into the result?"
            ),
        ),
    ]
