# Generated by Django 6.0.3 on 2026-04-03 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0036_tournament_max_judges_round1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="judge4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judge4_rounds",
                related_query_name="judge4_round",
                to="tourney.judge",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="judge5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judge5_rounds",
                related_query_name="judge5_round",
                to="tourney.judge",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="judge6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judge6_rounds",
                related_query_name="judge6_round",
                to="tourney.judge",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="judge7",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judge7_rounds",
                related_query_name="judge7_round",
                to="tourney.judge",
            ),
        ),
    ]
