# Generated by Django 6.0.3 on 2026-04-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0036_tournament_max_judges_round1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="randomize_prelims",
            field=models.BooleanField(
                default=False,
                help_text="Should Tabhard auto-generate all preliminary pairings and judges?",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="team_size",
            field=models.IntegerField(
                choices=[(2, "2-person teams"), (3, "3-person teams")],
                default=2,
                help_text="How many competitors may each team roster?",
            ),
        ),
    ]
