# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0037_tournament_randomize_prelims_tournament_team_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="predetermined_speakers",
            field=models.BooleanField(
                default=False,
                help_text="Predetermine speakers from roster order? First rostered competitor is Speaker 1 and second is Speaker 2.",
            ),
        ),
    ]
