# Generated by Django 6.0.3 on 2026-04-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0037_round_judge4_round_judge5_round_judge6_round_judge7"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="judge4",
        ),
        migrations.RemoveField(
            model_name="round",
            name="judge5",
        ),
        migrations.RemoveField(
            model_name="round",
            name="judge6",
        ),
        migrations.RemoveField(
            model_name="round",
            name="judge7",
        ),
    ]
