# Generated by Django 6.0.3 on 2026-04-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0038_tournament_predetermined_speakers"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairing",
            name="ballots_counted_override",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="additional_judges",
            field=models.ManyToManyField(
                blank=True,
                related_name="additional_rounds",
                related_query_name="additional_round",
                to="tourney.judge",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="locked_prelim_ballots",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="locked_prelim_cs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="locked_prelim_pd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="prelim_seed",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
