# Generated by Django 6.0.3 on 2026-04-30 05:15

from django.db import migrations
from django.db.models import Count


def remove_duplicate_pairings(apps, schema_editor):
    Pairing = apps.get_model("tourney", "Pairing")
    duplicates = (
        Pairing.objects.exclude(tournament_id=None)
        .values("tournament_id", "division", "round_num")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for duplicate in duplicates:
        pairings = Pairing.objects.filter(
            tournament_id=duplicate["tournament_id"],
            division=duplicate["division"],
            round_num=duplicate["round_num"],
        ).order_by("id")
        pairings.exclude(id=pairings.first().id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0039_pairing_ballots_counted_override_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_pairings, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="pairing",
            unique_together={("tournament", "division", "round_num")},
        ),
    ]
