# Generated by Codex on 2026-05-05

from django.db import migrations, models
import django.core.validators


def backfill_team_prelim_rounds(apps, schema_editor):
    Tournament = apps.get_model("tourney", "Tournament")
    for tournament in Tournament.objects.all():
        tournament.team_prelim_rounds = tournament.prelim_rounds
        tournament.save(update_fields=["team_prelim_rounds"])


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0040_alter_pairing_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="team_prelim_rounds",
            field=models.IntegerField(
                default=4,
                help_text="How many preliminary rounds should each team compete in?",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.RunPython(backfill_team_prelim_rounds, migrations.RunPython.noop),
    ]
