# Generated by Django 6.0.3 on 2026-05-06 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0041_tournament_team_prelim_rounds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="prelim_rounds",
            field=models.IntegerField(
                default=4,
                help_text="How many preliminary rounds are scheduled before elimination rounds?",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
