# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourney", "0042_alter_tournament_prelim_rounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="prelim_ballot_count_method",
            field=models.CharField(
                choices=[
                    ("random", "Randomly toss extra ballots"),
                    ("average", "Average extra ballots down to ballots counted"),
                ],
                default="random",
                help_text="How should extra preliminary ballots beyond ballots counted be handled?",
                max_length=20,
            ),
        ),
    ]
